name: bio3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - scipy
  - biopython
  - scikit-image
  - matplotlib
  - tk                    
  - igl=2.6.*
  - trimesh                
  - networkx            
  - pillow          
  - rtree      
  - shapely
  - openbabel 
  - mdanalysis
  - rdkit
  - psutil
  - tqdm
  - meshio
  - pip
  - pip:
    - prolif
    - pytest
    - pytest-cov
    - ruff
    - build
    - twine
